#!/bin/env bash

export POSIX="$HOME/.config/posix" # Works with sh/bash/zsh
export CURRENT_SHELL_NAME="$SHELL:t"
export CURRENT_SHELL_CONFIG_DIRECTORY="$HOME/.config/$CURRENT_SHELL_NAME"
export SETUP="$CURRENT_SHELL_CONFIG_DIRECTORY/setup"

command_exists() {
    command -v "$@" >/dev/null 2>&1
}

# shellcheck source="dot_config/posix/print_format.sh"
. "$POSIX/print_format.sh"

for file in "$CURRENT_SHELL_CONFIG_DIRECTORY"/plugins/*."CURRENT_SHELL_NAME"; do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

source "$POSIX/locale.sh"

if source "$POSIX/terminal_has_nerd_font.sh" -eq 0; then
    export YOU_ARE_USING_A_NERD_FONT="true"
    source "$CURRENT_SHELL_CONFIG_DIRECTORY/starship.zsh"
fi

# Set neovim as editor
if command_exists nvim; then
    export EDITOR=nvim
else
    echo "$(bold)$(red) Neovim is not installed!$(reset)"
fi

# Add shell scripts to PATH
export PATH="$PATH:$HOME/bin"

# Source the shared aliases file
source "$POSIX/aliases"

# Install/Activate Mise
source "$SETUP/mise"

# Go-lang-specific configuration
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# FZF Integration
source "$SETUP/fzf"

# Zoxide
source "$SETUP/zoxide"

# Tmux
source "$POSIX/tmux"

# Enable vi mode
bindkey -v

# Custom LS_COLORS settings
#export LS_COLORS="di=1;34:fi=0;37:ln=36:pi=33:so=32:bd=46;34:cd=46;34:or=31;43:mi=05;37;41"

case "$(uname -s)" in
Darwin)
    #####################
    ### MacOS CONFIG  ###
    #####################
    # Homebrew Ruby
    export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
    # Main Homebrew path
    export BREW_PATH="/opt/homebrew/bin"
    export PATH=$BREW_PATH:$PATH
    # Iterm2 shell integration
    if command_exists "/Applications/iTerm.app/Contents/MacOS/iTerm2"; then
        source "$SETUP/iterm2.zsh"
    fi
    # Ignore DS_Store files in git
    if [[ -x $HOME/.config/git/ignore ]]; then
        if command_exists git; then
            git config --global core.excludesfile "$HOME/.config/git/ignore"
        fi
    fi
    ;;
Linux)
    #####################
    ### LINUX CONFIG  ###
    #####################
    if [ -f /etc/os-release ]; then
        {
            . /etc/os-release
            case "$ID" in
            debian | ubuntu) ;;
            fedora) ;;
            arch) ;;
            *) ;;
            esac

        }
    fi
    ;;
*)
    fmt_error "OS=Unknown operating system"
    ;;
esac

if [[ $HOST == 'euge-mini' ]]; then
    #####################
    ## MOBILE DEV MAC ###
    #####################
    #-- Android Studio --
    if command_exists "/Applications/Android Studio.app/Contents/MacOS/studio"; then
        source "$POSIX/android_studio.sh"
    fi

    #-- LM Studio --
    if command_exists "/Applications/LM Studio.app/Contents/MacOS/LM Studio"; then
        export PATH="$PATH:$HOME/.lmstudio/bin"
    fi
fi

# Start the main tmux session
# A -> attach session if allready exists
# s -> session name
if [ -z "$TMUX" ]; then
    echo "Attaching to main session"
    tmux new -A -s main
fi
