#!/bin/env bash

export POSIX="$HOME/.config/posix" # Works with sh/bash/zsh
export CURRENT_SHELL_NAME="$SHELL:t"
export CURRENT_SHELL_CONFIG_DIRECTORY="$HOME/.config/$CURRENT_SHELL_NAME"
export SETUP="$CURRENT_SHELL_CONFIG_DIRECTORY/setup"

command_exists() {
    command -v "$@" >/dev/null 2>&1
}

# shellcheck source="dot_config/posix/print_format.sh"
. "$POSIX/print_format.sh"

for file in "$CURRENT_SHELL_CONFIG_DIRECTORY"/plugins/*; do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

source "$POSIX/locale.sh"

if source "$POSIX/terminal_has_nerd_font.sh"; then
    export YOU_ARE_USING_A_NERD_FONT="true"
    source "$SETUP/starship"
fi

# Set neovim as editor
if command_exists nvim; then
    export EDITOR=nvim
else
    echo "$(bold)$(red) Neovim is not installed!$(reset)"
fi

# Add shell scripts to PATH
export PATH="$PATH:$HOME/bin"

# Source the shared aliases file
source "$POSIX/aliases"

# Install/Activate Mise
source "$SETUP/mise"

# Go-lang-specific configuration
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# FZF Integration
source "$SETUP/fzf"

# Zoxide
source "$SETUP/zoxide"

# Tmux
source "$POSIX/tmux"

# Emacs
export PATH="$HOME/.config/emacs/bin:$PATH"
export DOOMDIR="$HOME/.config/doom"
export EMACSDIR="$HOME/.config/emacs"

# Antigravity
export PATH="/Users/euge/.antigravity/antigravity/bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/euge/.lmstudio/bin"
# End of LM Studio CLI section

# Added by Antigravity IDE
export PATH="/Users/euge/.antigravity-ide/antigravity-ide/bin:$PATH"

# Maestro cli (end-to-end testing)
export PATH=$PATH:$HOME/.maestro/bin

# Claude Code (don't want to pay extra for context)
export CLAUDE_CODE_DISABLE_1M_CONTEXT=1

# Enable vi mode
bindkey -v

# Custom LS_COLORS settings
#export LS_COLORS="di=1;34:fi=0;37:ln=36:pi=33:so=32:bd=46;34:cd=46;34:or=31;43:mi=05;37;41"

case "$(uname -s)" in
Darwin)
    #####################
    ### MacOS CONFIG  ###
    #####################
    # Homebrew Ruby
    export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
    # Main Homebrew path
    export BREW_PATH="/opt/homebrew/bin"
    export PATH=$BREW_PATH:$PATH
    # Java Open JDK
    export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
    # Iterm2 shell integration
    if command_exists "/Applications/iTerm.app/Contents/MacOS/iTerm2"; then
        source "$SETUP/iterm2.zsh"
    fi
    # Ignore DS_Store files in git
    if [[ -x $HOME/.config/git/ignore ]]; then
        if command_exists git; then
            git config --global core.excludesfile "$HOME/.config/git/ignore"
        fi
    fi
    # Homebrew gnu core utils
    alias gfind="/opt/homebrew/opt/findutils/libexec/gnubin/find"
    alias gtar="/opt/homebrew/opt/gnu-tar/libexec/gnubin/tar"
    alias gsed="/opt/homebrew/opt/gnu-sed/libexec/gnubin/sed"
    alias gls="/opt/homebrew/opt/coreutils/libexec/gnubin/ls"

    # Homebrew Emacs
    export EMACS_BIN="/opt/homebrew/bin/emacs"

    # Herd injected PHP 8.4 configuration.
    export HERD_PHP_84_INI_SCAN_DIR="/Users/euge/Library/Application Support/Herd/config/php/84/"

    # Herd injected NVM configuration
    export NVM_DIR="/Users/euge/Library/Application Support/Herd/config/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

    [[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"

    # Herd injected PHP binary.
    export PATH="/Users/euge/Library/Application Support/Herd/bin/":$PATH
    ;;
Linux)
    #####################
    ### LINUX CONFIG  ###
    #####################
    if [ -f /etc/os-release ]; then
        {
            . /etc/os-release
            case "$ID" in
            debian | ubuntu) ;;
            fedora) ;;
            arch) ;;
            *) ;;
            esac

        }
    fi
    ;;
*)
    fmt_error "OS=Unknown operating system"
    ;;
esac

if [[ $HOST == 'euge-mini' ]]; then
    #####################
    ## MOBILE DEV MAC ###
    #####################
    #-- Android Studio --
    if command_exists "/Applications/Android Studio.app/Contents/MacOS/studio"; then
        source "$POSIX/android_studio.sh"
    fi

    #-- LM Studio --
    if command_exists "/Applications/LM Studio.app/Contents/MacOS/LM Studio"; then
        export PATH="$PATH:$HOME/.lmstudio/bin"
    fi
fi

# Start the main tmux session
# A -> attach session if allready exists
# s -> session name
if [ -z "$TMUX" ]; then
    echo "Attaching to main session"
    tmux new -A -s main
fi
